// Common
export const SET_INFO_NOTIFICATION = "SET_INFO_NOTIFICATION ";
export const SET_ERROR_NOTIFICATION = "SET_ERROR_NOTIFICATION";
export const SET_SUCCESS_NOTIFICATION = "SET_SUCCESS_NOTIFICATION";
export const SET_SHOW_LOADER = "SET_SHOW_LOADER";

// Items
export const SET_ITEMS = "SET_ITEMS";
export const SET_ITEM = "SET_ITEM";
export const SET_ISLOADING = "SET_ISLOADING";
export const SET_ISSAVING = "SET_ISSAVING";
export const SET_APIRESPONSE_SUCCESS = "SET_APIRESPONSE_SUCCESS";
export const SET_APIRESPONSE_ERROR = "SET_APIRESPONSE_ERROR";
export const CLEAR_APIRESPONSE = "CLEAR_APIRESPONSE";
export const REMOVE_ITEM = "REMOVE_ITEM";
