export const SET_ITEMS = "SET_ITEMS";
export const SET_ITEM = "SET_ITEM";
export const SET_ISLOADING = "SET_ISLOADING";
export const SET_ISSAVING = "SET_ISSAVING";
export const SET_APIRESPONSE_SUCCESS = "SET_APIRESPONSE_SUCCESS";
export const SET_APIRESPONSE_ERROR = "SET_APIRESPONSE_ERROR";
export const CLEAR_APIRESPONSE = "CLEAR_APIRESPONSE";
export const REMOVE_ITEM = "REMOVE_ITEM";
